id: I086D09A3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:31:43+00:00'
last_modified: '2022-06-07T21:35:41.529201+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6403
  title: བཤེས་སྤྲིངསརྩ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3B70:
      image_group_id: I3CN6405
      title: ''
      total_pages: 136
      order: 1
      base_file: 3B70.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
