id: P004273
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:06:36.113743
source_metadata:
  id: bdr:W3CN6403
  title: བཤེས་སྤྲིངསརྩ་འགྲེལ།
  author: ''
  volumes:
    60c3d710a21a494bae131d8ce85bbb14:
      image_group_id: I3CN6405
      title: ''
      volume_number: 1
      total_pages: 136
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
